services:
  - type: web
    name: velours-parfums
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: velours-db
          property: connectionString
    
databases:
  - name: velours-db
    databaseName: velours
    user: velours_user
